#!/usr/bin/env python3
import os, json, urllib.request
from urllib.error import HTTPError

TOKEN = os.environ.get('TOKEN')
if not TOKEN:
    raise SystemExit('Set TOKEN env var to your Bearer token')

APP_ID = os.environ.get('APP_ID', '0538f210-83af-4474-9b03-812a0c15e1ce')
ORG_ID = os.environ.get('ORG_ID', '5371eb8c-30e7-48cc-91b2-4d1c4a389d79')
API_HOST = os.environ.get('API_HOST', 'https://staging.pigment.app')
BASE_APP = f"{API_HOST}/api/workspace/{APP_ID}"
BASE_WS = f"{API_HOST}/api/workspace"

BASE_DIM = os.environ.get('BASE_DIM', 'b6a69813-d214-4980-a2ec-7ffb348fbd43')  # Field 1
BASE_TX = os.environ.get('BASE_TX', '7f999943-b1d1-43b7-b5c4-7134323595a6')   # test rmodeler


def request(method, path, payload=None, base="app"):
    if path.startswith("http"):
        url = path
    else:
        root = BASE_APP if base == "app" else BASE_WS
        url = root + path
    data = json.dumps(payload).encode("utf-8") if payload is not None else None
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header("Authorization", f"Bearer {TOKEN}")
    if payload is not None:
        req.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(req) as resp:
            body = resp.read().decode("utf-8")
            return resp.status, json.loads(body) if body else None
    except HTTPError as e:
        body = e.read().decode("utf-8")
        raise SystemExit(f"HTTP {e.code} on {path}: {body}")


def list_all():
    return request("GET", "/list/ListForApplication")[1]


def get_list(list_id):
    return request("GET", f"/list/Get/{list_id}")[1]


def duplicate_list(list_id):
    path = f"/list/DuplicateList?listToDuplicateId={list_id}"
    status, resp = request("POST", path)
    return resp


def rename_list(list_id, new_name):
    # Try common payload shapes for rename
    try:
        request("PUT", f"/list/Rename/{list_id}", {"friendlyName": new_name})
    except SystemExit:
        request("PUT", f"/list/Rename/{list_id}", new_name)


def remove_property(list_id, prop_technical):
    request("DELETE", f"/list/{list_id}/property/Remove?propertyTechnicalName={prop_technical}")


def add_property(list_id, prop):
    request("POST", f"/list/{list_id}/property/Add", prop)


def update_default_property(list_id, prop_technical):
    request("PUT", f"/list/{list_id}/property/UpdateDefaultProperty", {"request": {"newDefaultPropertyTechnicalName": prop_technical}})


def update_display_property(list_id, prop_technical):
    # Endpoint expects a JSON string body.
    request("PUT", f"/list/{list_id}/property/UpdateDisplayProperty", prop_technical)


def add_rows(list_id, rows):
    payload = {"inputsOnExistingRows": [], "newRows": rows, "validateInputRows": True}
    request("PUT", f"/list/SetInputtedValuesWithNewRows?listId={list_id}", payload)


def list_views_on_block(block_id, block_type="List"):
    path = f"/internals/view/ListViewsOnBlock?organizationId={ORG_ID}&blockType={block_type}&blockId={block_id}"
    return request("GET", path, base="workspace")[1]


def create_view(underlying_id, underlying_type, name, description):
    payload = {
        "underlyingType": underlying_type,
        "underlyingId": underlying_id,
        "friendlyName": name,
        "description": description,
        "newView": {
            "underlyingType": underlying_type,
            "underlyingId": underlying_id,
            "friendlyName": name,
            "description": description
        }
    }
    return request("POST", "/view/CreateViewWithDefaultConfig", payload)[1]


def ensure_dup(existing, name, base_id):
    by_name = {l["friendlyName"].lower(): l for l in existing}
    by_id = {l["id"]: l for l in existing}
    key = name.lower()
    if key in by_name:
        return by_name[key]["id"]
    if base_id in by_id:
        list_id = by_id[base_id]["id"]
        rename_list(list_id, name)
        return list_id
    dup = duplicate_list(base_id)
    list_id = dup["id"]
    rename_list(list_id, name)
    return list_id


def main():
    existing = list_all()
    employee_id = ensure_dup(existing, "TI Employee", BASE_DIM)
    account_id = ensure_dup(existing, "TI Account", BASE_DIM)
    project_id = ensure_dup(existing, "TI Project", BASE_DIM)
    time_id = ensure_dup(existing, "TI Time Entry", BASE_TX)

    # Dimension lists: add a public Name property if missing, set default/display
    for lid in [employee_id, account_id, project_id]:
        lst = get_list(lid)
        props = {p["friendlyName"]: p for p in lst["properties"]}
        if "Name Public" not in props and "Name" not in props:
            add_property(lid, {"friendlyName":"Name Public","type":"Text","isUnique":False,"readableByEveryone":True,"isAutoGenerated":False})
            lst = get_list(lid)
            props = {p["friendlyName"]: p for p in lst["properties"]}
        pref = props.get("Name Public") or props.get("Name")
        update_default_property(lid, pref["technicalName"])
        update_display_property(lid, pref["technicalName"])

    # Project extra properties
    proj_list = get_list(project_id)
    proj_props = {p["friendlyName"] for p in proj_list["properties"]}
    if "Account" not in proj_props:
        add_property(project_id, {"friendlyName":"Account","type":"Dimension","referencedDimensionId":account_id,"isUnique":False,"readableByEveryone":True,"isAutoGenerated":False})
    if "Status" not in proj_props:
        add_property(project_id, {"friendlyName":"Status","type":"Text","isUnique":False,"readableByEveryone":True,"isAutoGenerated":False})
    if "Active" not in proj_props:
        add_property(project_id, {"friendlyName":"Active","type":"Boolean","isUnique":False,"readableByEveryone":True,"isAutoGenerated":False})

    # Time Entry list: ensure Date exists, remove old props, add required ones
    te_list = get_list(time_id)
    props = {p["friendlyName"]: p for p in te_list["properties"]}
    if "Date" not in props:
        add_property(time_id, {"friendlyName":"Date","type":"Date","isUnique":False,"readableByEveryone":True,"isAutoGenerated":False})

    desired = {"Date","Employee","Project","Account","Hours","Note","Status","Last Updated By","Last Updated At"}
    te_list = get_list(time_id)
    for p in te_list["properties"]:
        if p["friendlyName"] in desired:
            continue
        if p.get("isAutoGenerated"):
            continue
        if len(te_list["properties"]) <= 1:
            continue
        remove_property(time_id, p["technicalName"])

    te_list = get_list(time_id)
    props = {p["friendlyName"]: p for p in te_list["properties"]}
    if "Employee" not in props:
        add_property(time_id, {"friendlyName":"Employee","type":"Dimension","referencedDimensionId":employee_id,"isUnique":False,"readableByEveryone":True,"isAutoGenerated":False})
    if "Project" not in props:
        add_property(time_id, {"friendlyName":"Project","type":"Dimension","referencedDimensionId":project_id,"isUnique":False,"readableByEveryone":True,"isAutoGenerated":False})
    if "Account" not in props:
        add_property(time_id, {"friendlyName":"Account","type":"Dimension","referencedDimensionId":account_id,"isUnique":False,"readableByEveryone":True,"isAutoGenerated":False})
    if "Hours" not in props:
        add_property(time_id, {"friendlyName":"Hours","type":"Number","isUnique":False,"readableByEveryone":True,"isAutoGenerated":False})
    if "Note" not in props:
        add_property(time_id, {"friendlyName":"Note","type":"Text","isUnique":False,"readableByEveryone":True,"isAutoGenerated":False})
    if "Status" not in props:
        add_property(time_id, {"friendlyName":"Status","type":"Text","isUnique":False,"readableByEveryone":True,"isAutoGenerated":False})
    if "Last Updated By" not in props:
        add_property(time_id, {"friendlyName":"Last Updated By","type":"Text","isUnique":False,"readableByEveryone":True,"isAutoGenerated":False})
    if "Last Updated At" not in props:
        add_property(time_id, {"friendlyName":"Last Updated At","type":"Date","isUnique":False,"readableByEveryone":True,"isAutoGenerated":False})

    te_list = get_list(time_id)
    prop_date = next(p for p in te_list["properties"] if p["friendlyName"]=="Date")["technicalName"]
    update_default_property(time_id, prop_date)
    update_display_property(time_id, prop_date)

    # Seed Employee list
    emp_list = get_list(employee_id)
    emp_name_prop = next(p for p in emp_list["properties"] if p["friendlyName"] in ("Name Public","Name"))["technicalName"]
    employees = ["Fran", "Rober", "Aurel", "Max", "Jeff", "Ahmed", "Jeremy", "Thomas", "Mathieu", "Franck"]
    rows = [{"inputs":[{"propertyTechnicalName": emp_name_prop, "newValue": n}]} for n in employees]
    add_rows(employee_id, rows)

    # Seed Account list with Internal
    acct_list = get_list(account_id)
    acct_name_prop = next(p for p in acct_list["properties"] if p["friendlyName"] in ("Name Public","Name"))["technicalName"]
    add_rows(account_id, [{"inputs":[{"propertyTechnicalName": acct_name_prop, "newValue": "Internal"}]}])

    # Create Board
    views_time = list_views_on_block(time_id, "List")
    views_project = list_views_on_block(project_id, "List")
    time_view_id = views_time[0]["id"] if views_time else None
    proj_view_id = views_project[0]["id"] if views_project else None
    if not time_view_id:
        time_view_id = create_view(time_id, "List", "TI Time Entry", "Time entry input")["id"]
    if not proj_view_id:
        proj_view_id = create_view(project_id, "List", "TI Projects", "Projects and account mapping")["id"]

    board_payload = {
        "name": "Time Input",
        "description": "Timesheet entry and project maintenance",
        "icon": "Input",
        "iconColor": "Blue",
        "boardSharingStatus": "Private",
        "blocks": [
            {
                "blockId": time_view_id,
                "blockType": "View",
                "boardBlockPosition": {"x": 0, "y": 0, "width": 8, "height": 10},
                "viewBoardBlockConfig": {
                    "boardBlockDisplayType": "Table",
                    "contentId": time_view_id,
                    "title": "Time Entry",
                    "showTitle": True,
                    "allowAddingNewItemsFromWidget": True
                }
            },
            {
                "blockId": proj_view_id,
                "blockType": "View",
                "boardBlockPosition": {"x": 8, "y": 0, "width": 4, "height": 10},
                "viewBoardBlockConfig": {
                    "boardBlockDisplayType": "Table",
                    "contentId": proj_view_id,
                    "title": "Projects",
                    "showTitle": True,
                    "allowAddingNewItemsFromWidget": True
                }
            }
        ]
    }
    status, board_resp = request("POST", "/board/Create", board_payload)

    print(json.dumps({
        "employee_list_id": employee_id,
        "account_list_id": account_id,
        "project_list_id": project_id,
        "time_entry_list_id": time_id,
        "time_entry_view_id": time_view_id,
        "project_view_id": proj_view_id,
        "board_id": board_resp.get("id")
    }, indent=2))

if __name__ == '__main__':
    main()
